version: '3.8'

services:
  base-db:
    build:
      context: ./docker
      dockerfile: Dockerfile-mysql
    image: base-db:1.0
    container_name: base-db
    networks:
      - base
    ports:
      - "23306:23306"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./db/ddl/00_create_database.sql:/docker-entrypoint-initdb.d/00_create_database.sql
      - ./db/ddl/01_create_user.sql:/docker-entrypoint-initdb.d/01_create_user.sql
      - ./docker/mysql_data:/var/lib/mysql
  base-redis:
    build:
      context: ./docker
      dockerfile: Dockerfile-redis
    image: base-redis:1.0
    container_name: base-redis
    networks:
      - base
    ports:
      - "26379:26379"
  base-minio:
    build:
      context: ./docker
      dockerfile: Dockerfile-minio
    image: base-minio:1.0
    container_name: base-minio
    networks:
      - base
    ports:
      - "29090:9000"
      - "29092:9002"
    volumes:
      - ./docker/files/minio/data:/data
      - ./docker/files/minio/export:/export
      - ./docker/files/minio/config:/root/.minio
      - ./docker/files/minio/policies:/policies
    entrypoint: sh
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
      cp -r /policies/* /data/.minio.sys/;
      cp -r /export/* /data/;
      minio server /data --console-address ":9002";
      "
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
  base-node-red:
    build:
      context: ./docker
      dockerfile: Dockerfile-nodered
    image: base-nodered:1.0
    environment:
      - TZ='Asia/Tokyo'
    container_name: base-nodered
    networks:
      - base
    ports:
      - "21880:1880"
    volumes:
      - ./docker/files/node-red/data:/data
  api-doc:
    image: redocly/redoc:v2.1.3
    volumes:
      - ./api/doc:/usr/share/nginx/html/api
    environment:
      SPEC_URL: api/openapi.yaml
      PAGE_TITLE: "API Doc"
      PORT: 3000
    container_name: api-doc
    ports:
      - "3000:3000"

  base-db-test:
    depends_on:
      - base-db
    image: base-db:1.0
    container_name: base-db-test
    networks:
      - base
    command: --port 13306
    ports:
      - "13306:13306"
    volumes:
      - ./db/ddl/00_create_database.sql:/docker-entrypoint-initdb.d/00_create_database.sql
      - ./db/ddl/01_create_user.sql:/docker-entrypoint-initdb.d/01_create_user.sql
      - ./db/ddl/migration/V1_0_0__create_table.sql:/docker-entrypoint-initdb.d/V1_0_0__create_table.sql
  base-redis-test:
    depends_on:
      - base-redis
    image: base-redis:1.0
    container_name: base-redis-test
    command: --port 16379
    networks:
      - base
    ports:
      - "16379:16379"
networks:
  base:
    driver: bridge
