FROM public.ecr.aws/docker/library/amazoncorretto:21.0.2-alpine

USER 1000:1000
COPY --chown=1000:1000 batch/build/libs/base-batch.jar /app/app.jar
COPY --chown=1000:1000 docker/bin/entrypoint.sh /app/entrypoint.sh
RUN chmod 755 /app/entrypoint.sh

ENV TZ=Asia/Tokyo

WORKDIR /app

EXPOSE 8080

ENTRYPOINT ["/bin/sh", "-c", "./entrypoint.sh"]